### PR TITLE
fixed typos & German translation

### PR DESCRIPTION
**Pull request by niccokunzmann**
Hello, I removed typos.

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@gnunicorn @lehmannro Are you still responslibe for this repositpry? Jugend Hackt and CoderDojo also use the slides. I translated them to give easier access to German-only Mentors e.g. child mentors. Would you like to merge this?

If you like me to review other PRs, please add me to the organization or the repositories which I should watch. I am looking at Github messages and like to improve the material if that qualifies.
Viele Grüße,
Nicco

**Comment by skade** [comment]
@niccokunzmann I at least know that Ben is currently not that involved in OTS. Maybe @xMartin can shed some light in here?

Thanks for the offer to do review work \o/.

**Comment by niccokunzmann** [comment]
@lehmannro Can you grant me permissions. I will not abuse them.

**Comment by phumberdroz** [comment]
hey @xMartin can you take a look at this again?

Best

**Comment by xMartin** [comment]
@niccokunzmann Thanks a lot! Will merge and grant permissions.

**Comment by niccokunzmann** [comment]
Thanks to all! I want to maintain it. The OpenTechSchool Coaching Guide is used by CoderDojo and Jugend Hackt too and maybe more than I know.

**Pull request merged**
